package service

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/jiazhen-lin/flight-booking/internal/domain"
	"github.com/shopspring/decimal"
	"github.com/sirupsen/logrus"
	"golang.org/x/sync/singleflight"
)

type SearchFilter struct {
	DepartureAirportID domain.AirportID
	ArrivalAirportID   domain.AirportID
	DepartureDate      time.Time
	Cursor             string
	Limit              int
}

type BookParams struct {
	Seats []domain.FlightSeats
}

type FlightService interface {
	// Search returns a list of flight plans based on the given parameters.
	Search(ctx context.Context, filter SearchFilter) (paths []domain.FlightPath, nextCursor string, err error)
	// Book books specific flights for the given parameters.
	Book(ctx context.Context, params BookParams) error
}

type flightService struct {
	repo  domain.FlightRepository
	group singleflight.Group
}

var _ FlightService = (*flightService)(nil)

func NewFlightService(repo domain.FlightRepository) *flightService {
	return &flightService{repo: repo}
}

func (s *flightService) Search(ctx context.Context, filter SearchFilter) ([]domain.FlightPath, string, error) {
	// TODO: implement redis cache for distributed architecture
	// There are two types of cache:
	// 1. cache the pre-estimated paths per day for every city to another, the cache can be generated by a deamon service
	//	redis data type: ZSET
	//  key name: flight_paths_{departure_airport_id}_{arrival_airport_id}_{departure_date}_{strategy}
	//  	- now we only have 1 strategy to order the path by its total flight duration, so the strategy is "duration"
	//  member: paths, each path is a list of flight id
	//		- flight metadata is cached in another redis hash set
	//  score: strategy value (total flight duration)
	// 2. cache the flight metadata, if there is a new booking for a flight, we will evict cache

	// Use singleflight to avoid concurrently duplicate estimation
	key := fmt.Sprintf("flight_paths_%d_%d_%s", filter.DepartureAirportID, filter.ArrivalAirportID, filter.DepartureDate.Format(time.DateOnly))
	departureTimeFrom := filter.DepartureDate

	v, err, _ := s.group.Do(key, func() (interface{}, error) {
		// Now we only have 1 strategy to order the path by its total flight duration, so the first path is the shortest path
		return s.estimatePaths(ctx, filter.DepartureAirportID, filter.ArrivalAirportID, departureTimeFrom)
	})
	if err != nil {
		return nil, "", err
	}
	paths := v.([]domain.FlightPath)

	// parse cursor to implement pagination
	var offset int
	if filter.Cursor != "" {
		offset, err = strconv.Atoi(filter.Cursor)
		if err != nil {
			// ignore cursor error
			logrus.Errorf("parse cursor: %+v, error: %+v", filter.Cursor, err)
		} else if offset >= len(paths) {
			// ignore out of range cursor
			offset = 0
			logrus.Errorf("out of range cursor: %+v", filter.Cursor)
		}
	}
	paths = paths[offset:]
	limit := filter.Limit
	var nextCursor string
	if len(paths) > limit {
		nextCursor = strconv.Itoa(offset + limit)
		paths = paths[:limit]
	}

	return paths, nextCursor, nil
}

func (s *flightService) estimatePaths(ctx context.Context, source, target domain.AirportID, departureTime time.Time) ([]domain.FlightPath, error) {
	// load all flights from db to find all the possible edges for the graph
	var flights []domain.Flight

	from, to := departureTime, departureTime.AddDate(0, 0, 2) // try to find the next 2 days flights
	var lastID int64
	availableSeats := true
	for i := 0; i < 10000; i++ { // add a limitation for loop
		filter := domain.ListFilter{
			DepartureTimeFrom: from,
			DepartureTimeTo:   to,
			AvailableSeats:    &availableSeats,
			Limit:             500,
		}
		if lastID != 0 {
			filter.CursorID = &lastID
		}
		tmp, err := s.repo.List(ctx, filter)
		if err != nil {
			return nil, err
		}
		if len(tmp) == 0 {
			break
		}
		flights = append(flights, tmp...)
		lastID = tmp[len(tmp)-1].ID
		if tmp[len(tmp)-1].DepartureTime.After(from) {
			from = tmp[len(tmp)-1].DepartureTime
		}
	}
	logrus.Infof("total available flights: %d", len(flights))

	// estimate the first N shortest paths
	paths, err := findShortestNPaths(flights, source, target, departureTime, departureTime.AddDate(0, 0, 1), 100)
	if err != nil {
		return nil, err
	}
	logrus.Infof("src: %d, target: %d, departureTime: %s, estimated paths: %d", source, target, departureTime.Format(time.DateOnly), len(paths))

	flightPaths := make([]domain.FlightPath, len(paths))
	for i, p := range paths {
		var price decimal.Decimal
		for _, f := range p.flights {
			price = price.Add(f.Price)
		}

		flightPaths[i] = domain.FlightPath{
			Flights:         p.flights,
			Price:           price,
			DurationSeconds: p.durationSeconds,
		}
	}

	return flightPaths, nil
}

func (s *flightService) Book(ctx context.Context, params BookParams) error {
	if err := s.repo.Book(ctx, params.Seats); err != nil {
		return err
	}
	return nil
}
